name: Version Update

on:
  pull_request_target:
    branches:
      - main

jobs:
  version-update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Update version
      run: |
        if [[ "$(cat package.json | grep version | cut -d'"' -f4)" != *".0."* ]]; then
          npm version patch
        fi
        git add package.json package-lock.json
        git commit -m "chore: update version to $(cat package.json | grep version | cut -d'"' -f4)"
        git push origin main
    - name: Create tag
      run: |
        git tag -a $(cat package.json | grep version | cut -d'"' -f4) -m "Release $(jq -r '.version' package.json)"
        git push origin main --tags
