name: Bump Version

on:
  pull_request_target:
    branches:
      - main
      - test-branch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Bump version
        run: npm version patch --no-git-tag-version

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📦 Bump a new version"
          file_pattern: "package.json package-lock.json"
          commit_user_name: "GitHub Actions"
          
