name: Bump Version

on: [pull_request]

jobs:
  versioning:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Bump version
        id: bump_version
        run: |
          VERSION=$(npm version patch --no-git-tag-version)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📦 Bump a new version"
          tagging_message: "${{ env.version }}"
          push_options: "--tags"
